config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  get 'about/index'
  get 'contact/index'
  get 'home/index'
  get 'welcome/index'
  get '/search', to: 'posts#search'
  
  resources :tags
  resources :posts
  devise_for :users
  root to: 'home#index'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :featured_image
  has_rich_text :content

  has_many :tags
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :author, presence: true, length: { minimum: 6, maximum: 25 }

  acts_as_taggable_on :tags
  acts_as_punchable
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }, inclusion: { in: %w[gabrielogomes@live.com]}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order("created_at desc").page(params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.order("created_at desc").page(params[:page])
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.punch(request)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.author = current_user.name
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :featured_image, :content, :user_id, :tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: :show

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
    @posts = Post.tagged_with(@tag.name).order("created_at desc").page(params[:page])
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def find_tag_by_name(tag)
    Tag.find_by_name(tag).id
  end

  def most_used_tags
    Tag.order("taggings_count asc").last(10)
  end
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/home/index.html.erb
<article class="tile is-child">
  <p class="title">Publicações mais recentes</p>
  <div class="content">
    <div class="container">
      <% @posts.each do |post| %>
        <div class="card mb-2">
          <% if post.featured_image.attached? %>
            <div class="card-image">
              <figure class="image is-full is-3by1">
                <%= image_tag post.featured_image %>
              </figure>
            </div>
          <% end %>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <a href="<%= post_path(id: post.id) %>"><p class="title is-4"><%= post.title %></p></a>
              </div>
            </div>
            <p>
              <%= truncate(strip_tags(post.content.to_s), length: 120) %> <%= link_to "Leia mais", post_path(post) %>
            </p>
            <p>Autor: <%= post.author %> </p>
            <p>Visualizações: <%= post.hits %></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="columns is-centered is-mobile">
      <div class="column is-two-thirds-mobile m-2">
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</article>
    

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
 
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="file">
    <label class="file-label">
      <%= form.file_field :featured_image, class: 'file-input' %>
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Escolha a imagem de destaque…
        </span>
      </span>
    </label>
  </div>

  <div class="field">
    <%= form.label 'Título', class: 'label' %>
    <div class="control">
      <%= form.text_field :title, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label 'Categorias', class: 'label' %>
    <div class="control">
      <%= form.text_field :tag_list.to_s, value: form.object.tag_list.to_s, class: 'input' %>
    </div>
  </div>
 
  <div class="field">
    <%= form.label 'Conteúdo', class: 'label' %>
    <%= form.rich_text_area :content %>
  </div>
 
  <div class="field is-grouped">
    <div class="control">
      <%= form.submit 'Criar', class: 'button is-link' %>
    </div>
    <div class="control">
      <%= link_to 'Voltar', posts_path, class: 'button is-link is-light' %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %> | 
<%= link_to 'Delete', @post, method: :delete %>

app/views/posts/index.html.erb
<div class="container is-centered">
  <h1 class="title is-size-4 has-text-centered is-family-sans-serif is-underlined">Todas Públicações</h1>

  <% @posts.each do |post| %>
    <div class=" is-full-mobile is-two-thirds-tablet is-half-desktop is-one-third-widescreen ">
      <div class="card m-2">
        <% if post.featured_image.attached? %>
          <div class="card-image">
            <figure class="image is-full  is-3by1">
              <%= image_tag post.featured_image %>
            </figure>
          </div>
        <% end %>
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <a href="<%= post_path(id: post.id) %>"><p class="title is-4"><%= post.title %></p></a>
            </div>
          </div>
          <p>
            <%= truncate(strip_tags(post.content.to_s), length: 120) %> <%= link_to "Leia mais", post_path(post) %>
          </p>
          <p>Autor: <%= post.author %> </p>
          <p>Visualizações: <%= post.hits %></p>
        </div>
      </div>
    </div>
  <% end %>
  <div class="columns is-centered is-mobile">
    <div class="column is-two-thirds-mobile m-2">
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="title is-1">Nova Publicação</h1> 
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="column">
    <% if @post.featured_image.attached? %>
      <figure class="image is-3by1">
        <%= image_tag @post.featured_image %>
      </figure>
    <% end %>
    <div class="columns">
      <div class="column">
        <p class="title"><%= @post.title %></p>
        <% @post.tag_list.each do |tag| %>
          <p class="tag has-text-white is-link is-italic is-info"><%= link_to tag, tag_path(id: find_tag_by_name(tag))%></p>
        <% end %>
        <p>Visualizações: <%= @post.hits %></p>
        <p><strong> Por: </strong><%= @post.author %></p>
        <p><strong> Publicado em: </strong> <%= @post.created_at.strftime("%d/%m/%Y") %></p>
        <% if @post.updated_at.strftime("%d/%m/%Y") != @post.created_at.strftime("%d/%m/%Y") %>
          <p><strong> Editado em: </strong> <%= @post.updated_at.strftime("%d/%m/%Y") %></p>
        <% end %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <%= @post.content %>
      </div>
    </div>
    <div class="columns m-3 p-1 is-flex is-align-items-center is-justify-content-end share-buttons">
      <div 
        class="fb-share-button column is-1"
        data-href="https://livrosexplosivos.herokuapp.com/posts/<%= @post.id %>" 
        data-layout="button" 
        data-size="large">
          <a 
            target="_blank" 
            href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Flivrosexplosivos.herokuapp.com%2F&amp;src=sdkpreparse" 
            class="fb-xfbml-parse-ignore">Compartilhar
          </a>
      </div>

      <a 
        href="https://twitter.com/intent/tweet?text=Acabei%20de%20ler%20o%20post%20<%= @post.title %>.%20Leia%20também%20em%20https://livrosexplosivos.herokuapp.com/posts/<%= @post.id %>&button_hashtag=LivrosExplosivos&ref_src=twsrc%5Etfw" 
        class="twitter-hashtag-button column is-1" 
        data-show-count="false">Tweet #LivrosExplosivos</a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>  
    <div class="columns">
      <div class="column">
        <div id="disqus_thread"></div>
        <script>
            /**
            *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
            *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
            
            var disqus_config = function () {
            this.page.url = "http://livrosexplosivos.herokuapp.com/posts/<%= @post.id %>";;  // Replace PAGE_URL with your page's canonical URL variable
            this.page.identifier = "post<%= @post.id %>"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            };
            
            (function() { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://https-livrosexplosivos-com.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer pb-1 has-background-dark has-text-white">
  <div class="container socials-links">
    
  </div>
  <div class="container is-size-7 mb-6">
    <p>
      © 2022 - Livros Explosivos por Gabriel Gomes. Todos os direitos reservados. <%= link_to 'Política de Privacidade', root_path %> | <%= link_to 'Termos de Uso', root_path %> 
    </p>
    <p>
      Os produtos apresentados estão sujeitos a variações de preço conforme determinação dos respectivos e-commerces
    </p>
  </div>
  <div class="container rights">
    <p class="has-text-right">
      Feito pelo <a href="https://gabrielgo.dev" target="_blank">Gabigol</a>.
    </p>
  </div>
</footer>

app/views/shared/_logo.html.erb
<section class="section is-medium is-flex is-align-items-center is-justify-content-center has-background-dark p-6 mb-6">
  <figure class="image">
    <%= image_tag 'EXPLOSIVOS.png', :class => 'logo-img', :alt => 'Logo' %>
  </figure>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar container" role="navigation" aria-label="main-navigation">
  <div class="navbar-brand is-flex is-align-items-center is-justify-content-center">
    <a class='ml-5' href="https://www.instagram.com/livrosexplosivos" target="_blank"><i class="fa fa-instagram navbar-item"></i></a>
    <a href="https://twitter.com/gabigol84" target="_blank"><i class="fa fa-twitter navbar-item"></i></a>
    <a href="https://t.me/+bJxg1DTuSPEzNzIx" target="_blank"><i class="fa fa-telegram navbar-item"></i></a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">  
      <%= link_to "Início", root_path, class: 'navbar-item' %>
      
      <%= link_to "Sobre", about_index_path, class: 'navbar-item' %>
      <%= link_to "Contato", contact_index_path, class: 'navbar-item' %>

      <% if user_signed_in? %>
        <%= link_to "+ Nova Publicação", new_post_path, class: 'navbar-item'  %>
        <%= link_to "Sair", destroy_user_session_path, method: :delete, class: 'navbar-item'  %>
      <% end %>

      <div class="navbar-item field">
        <p class="control has-icons-right">
          <input class="input" type="text" placeholder="Digite e busque algo">
          <span class="icon is-small is-right">
            <i class="fa fa-search"></i>
          </span>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_search.html.erb
<div class="field">
  <p class="control has-icons-right">
    <input class="input" type="text" placeholder="Digite e busque algo">
    <span class="icon is-small is-right">
      <i class="fa fa-search"></i>
    </span>
  </p>
</div>

app/views/shared/_sidebar.html.erb
<div class="container">
  <div class="container mb-5 is-flex is-align-items-center is-justify-content-center">
    <i class="p-3 fa fa-telegram telegram has-text-info"></i>
    <a class="" href="https://t.me/+bJxg1DTuSPEzNzIx" target="_blank">
      Siga o nosso canal no Telegram
    </a>
  </div>

  <div class="container mb-5 register-newsletter is-flex is-flex-direction-column is-align-items-center">
    <h4 class="title is-5">Inscreva-se na nossa Newsletter!</h3>
    <div class="field">
      <div class="control">
        <input class="input" type="text" placeholder="Informe seu nome">
      </div>
    </div>
    <div class="field">
      <div class="control">
        <input class="input" type="text" placeholder="Digite seu e-mail">
      </div>
    </div>
    <div class="control">
      <a class="button is-info">
        Inscrever-se!
      </a>
    </div>
  </div>

  <div class="container mb-5 recommended-books">
    <h3 class="title is-4 is-flex is-flex-direction-column is-align-items-center">Livros Explosivos</h3>
    <div class="is-flex is-flex-direction-column is-align-items-center">
      <h4 class="title is-6 mb-1">Ilha do Tesouro</h4>
      <a href="https://www.amazon.com.br/ilha-tesouro-Robert-Louis-Stevenson/dp/8551303171?_encoding=UTF8&pd_rd_w=dsBpz&pf_rd_p=0176cc1c-3906-4862-a364-fa46bdca93ef&pf_rd_r=HBFMSDKT3520S7390YAV&pd_rd_r=f665e7f7-0b9d-4625-ab61-ef24d02dc4ce&pd_rd_wg=IGHHF&linkCode=li2&tag=descontamazon-20&linkId=b22970d1e2b4f9531f4a9922fb50db23&language=pt_BR&ref_=as_li_ss_il" target="_blank"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=8551303171&Format=_SL160_&ID=AsinImage&MarketPlace=BR&ServiceVersion=20070822&WS=1&tag=descontamazon-20&language=pt_BR" ></a><img src="https://ir-br.amazon-adsystem.com/e/ir?t=descontamazon-20&language=pt_BR&l=li2&o=33&a=8551303171" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
      
      <h4 class="title is-6 mb-1 mt-3">O Grande Gatsby</h4>
      <a href="https://www.amazon.com.br/Grande-Gatsby-Exclusivo-Amazon/dp/6586490049?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3J5FGSL8OI6UQ&keywords=o+grande+gatsby&qid=1647911972&s=books&sprefix=o+grande+gatsb%2Cstripbooks%2C247&sr=1-2&ufe=app_do%3Aamzn1.fos.6d798eae-cadf-45de-946a-f477d47705b9&linkCode=li2&tag=descontamazon-20&linkId=4dc608d7f8580c8f3afbf13bb79cdf5b&language=pt_BR&ref_=as_li_ss_il" target="_blank"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=6586490049&Format=_SL160_&ID=AsinImage&MarketPlace=BR&ServiceVersion=20070822&WS=1&tag=descontamazon-20&language=pt_BR" ></a><img src="https://ir-br.amazon-adsystem.com/e/ir?t=descontamazon-20&language=pt_BR&l=li2&o=33&a=6586490049" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
      
      <h4 class="title is-6 mb-1 mt-3">Box O Castelo Animado</h4>
      <a href="https://www.amazon.com.br/castelo-animado-Diana-Wynne-Jones/dp/8501304352?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3NGKQ21SXCJ05&keywords=castelo+animado&qid=1647912000&s=books&sprefix=castelo+animad%2Cstripbooks%2C190&sr=1-1&ufe=app_do%3Aamzn1.fos.6121c6c4-c969-43ae-92f7-cc248fc6181d&linkCode=li2&tag=descontamazon-20&linkId=b2cafdde98e5b80a31ebbb041cd5bf2d&language=pt_BR&ref_=as_li_ss_il" target="_blank"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=8501304352&Format=_SL160_&ID=AsinImage&MarketPlace=BR&ServiceVersion=20070822&WS=1&tag=descontamazon-20&language=pt_BR" ></a><img src="https://ir-br.amazon-adsystem.com/e/ir?t=descontamazon-20&language=pt_BR&l=li2&o=33&a=8501304352" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
      
      <h4 class="title is-6 mb-1 mt-3">Box Musashi</h4>
      <a href="https://www.amazon.com.br/Musashi-Box-volumes-Eiji-Yoshikawa/dp/8574481505?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1WAOK8CQSSESJ&keywords=musashi&qid=1647912019&s=books&sprefix=musash%2Cstripbooks%2C208&sr=1-3&ufe=app_do%3Aamzn1.fos.fcd6d665-32ba-4479-9f21-b774e276a678&linkCode=li2&tag=descontamazon-20&linkId=dabca12fa3063699eae09ba840831b17&language=pt_BR&ref_=as_li_ss_il" target="_blank"><img border="0" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=8574481505&Format=_SL160_&ID=AsinImage&MarketPlace=BR&ServiceVersion=20070822&WS=1&tag=descontamazon-20&language=pt_BR" ></a><img src="https://ir-br.amazon-adsystem.com/e/ir?t=descontamazon-20&language=pt_BR&l=li2&o=33&a=8574481505" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
    </div>
    <p class="is-size-7 mt-2"><strong>Aviso:</strong> ao comprar através dos links acima estaremos recebendo uma pequena comissão. Esse valor não aumenta no custo final do produto.</p>
  </div>

  <div class="is-hidden container mb-5 recommended-books">
    <h3 class="title is-4">Anúncios</h3>

  </div>

  <div class="container ">
    <h3 class="title is-4">Tags mais lidas</h3>
    <div class="block">
      <% most_used_tags.each do |tag| %>
        <span class="tag has-text-white is-italic is-info"><%= link_to tag.name, tag_path(id: find_tag_by_name(tag.name))%></span>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
 <div class="container page-content is-centered">
  <h1 class="title has-text-centered is-4">Publicações com a tag <span class="is-italic"><%= @tag.name %> </h1 class="title">
  <% @posts.each do |post| %>
    <div class=" is-full-mobile is-two-thirds-tablet is-half-desktop is-one-third-widescreen ">
      <div class="card m-2">
        <% if post.featured_image.attached? %>
          <div class="card-image">
            <figure class="image is-full  is-3by1">
              <%= image_tag post.featured_image %>
            </figure>
          </div>
        <% end %>
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <a href="<%= post_path(id: post.id) %>"><p class="title is-4"><%= post.title %></p></a>
            </div>
          </div>
          <p>
            <%= truncate(strip_tags(post.content.to_s), length: 120) %> <%= link_to "Leia mais", post_path(post) %>
          </p>
          <p>Autor: <%= post.author %> </p>
          <p>Visualizações: <%= post.hits %></p>
        </div>
      </div>
    </div>
  <% end %>
  <div class="columns is-centered is-mobile">
    <div class="column is-two-thirds-mobile m-2">
      <%= paginate @posts %>
    </div>
  </div>
</div>
</p>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_tag_path(@tag) %> |
  <%= link_to 'Back', tags_path %>
<% end %>